import { GenreModal } from "../modals/Modals";


export const FETCH_GENRELIST = 'FETCH_GENRELIST';
export const FETCH_GENRELIST_SUCCESS = 'FETCH_GENRELIST_SUCCESS';
export const FETCH_GENRELIST_ERROR = 'FETCH_GENRELIST_ERROR';
export const FETCH_NOW_PLAYING_LIST = 'FETCH_NOW_PLAYING_LIST';
export const FETCH_NOW_PLAYING_LIST_SUCCESS = 'FETCH_NOW_PLAYING_LIST_SUCCESS';
export const FETCH_NOW_PLAYING_LIST_ERROR = 'FETCH_NOW_PLAYING_LIST_ERROR';
export const FETCH_TOP_RATED_LIST = 'FETCH_TOP_RATED_LIST';
export const FETCH_TOP_RATED_LIST_SUCCESS = 'FETCH_TOP_RATED_LIST_SUCCESS';
export const FETCH_TOP_RATED_LIST_ERROR = 'FETCH_TOP_RATED_LIST_ERROR';
export const FETCH_UPCOMING_LIST = 'FETCH_UPCOMING_LIST';
export const FETCH_UPCOMING_LIST_SUCCESS = 'FETCH_UPCOMING_LIST_SUCCESS';
export const FETCH_UPCOMING_LIST_ERROR = 'FETCH_UPCOMING_LIST_ERROR';
export const FETCH_POPULAR_LIST = 'FETCH_POPULAR_LIST';
export const FETCH_POPULAR_LIST_SUCCESS = 'FETCH_POPULAR_LIST_SUCCESS';
export const FETCH_POPULAR_LIST_ERROR = 'FETCH_POPULAR_LIST_ERROR';

export const fetchGenre = ( ) =>({type: FETCH_GENRELIST})

export const fetchGenreList = (type: string , payload: GenreModal[] | string ) => ({
    type,
    payload
  });


  